api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

import views as api_views


urlpatterns = [
    url(r'^feedback/new/$', api_views.create_feedback),
    url(r'^books/$', api_views.books),
]

apps/base/urls.py
from django.conf.urls import url
from views import home

urlpatterns = [url(r'^$', home, name='home'), ]

apps/legoteka/urls.py
from django.conf.urls import url
from views import home, legoteka_by_category

urlpatterns = [url(r'^$', home, name='home'),
               url(r'^(?P<pk>\d+)/$', legoteka_by_category, name='by_category'),]

apps/library/urls.py
from django.conf.urls import url
from views import book_list

urlpatterns = [url(r'^$', book_list, name='home'), ]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from project import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.base.urls', namespace='base')),
    url(r'^legoteka/', include('apps.legoteka.urls', namespace='legoteka')),
    url(r'^humanitarian_aid/', include('apps.aid.urls', namespace='humanitarian_aid')),
    url(r'^library/', include('apps.library.urls', namespace='library')),
    url(r'^financial/', include('apps.financial.urls', namespace='financial')),
    url(r'^api/', include('api.urls')),
    url(r'^pages/(\S+)/$', 'apps.pages.views.pages_detail', name='pages_detail'),
    url(r'^redactor/', include('redactor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/aid/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models


class AidType(models.Model):
    title = models.CharField(u'Название', max_length=60)

    class Meta:
        verbose_name = u'тип гуманитарной помощь'
        verbose_name_plural = u'типы гуманитарной помощи'

    def __unicode__(self):
        return self.title

TYPES = (
    ('1', 'Детям'),
    ('2', 'Центру'),
)


class HumanitarianAidForKid(models.Model):
    title = models.CharField(u'Название', max_length=60)
    description = models.TextField(u'Описание')

    class Meta:
        verbose_name = u'гуманитарная помощь родителям'
        verbose_name_plural = u'гуманитарная помощь родителям'

    def __unicode__(self):
        return self.title


class HumanitarianAidForSponsors(models.Model):
    title = models.CharField(u'Название', max_length=60)
    type = models.CharField(u"Кому?", max_length=1, default=1, choices=TYPES)
    description = models.TextField(u'Описание')

    class Meta:
        verbose_name = u'для потенциальных спонсоров'
        verbose_name_plural = u'для потенциальных спонсоров'

    def __unicode__(self):
        return self.title


class AidRequest(models.Model):
    aid_item = models.ForeignKey(HumanitarianAidForKid, verbose_name=u'Гуманитарная помощь')
    name = models.CharField(u"ФИО", max_length=255)
    contacts = models.CharField("Телефон или email", max_length=255)
    note = models.CharField(u"Примечание", max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = u'заявка на получение гум помощи'
        verbose_name_plural = u'заявки на получение гум помощи'

    def __unicode__(self):
        return self.name


class GivingAid(models.Model):
    name = models.CharField(u"ФИО", max_length=255)
    contacts = models.CharField("Телефон или email", max_length=255)
    message = models.TextField(u"Сообщение", max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = u'заявка на оказание гум помощи'
        verbose_name_plural = u'заявки на оказание гум помощи'

    def __unicode__(self):
        return self.name

apps/base/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from redactor.fields import RedactorField


class News(models.Model):
    title = models.CharField(u"Заголовок", max_length=255)
    photo = models.ImageField(u"Фотография", upload_to='news/')
    text = models.CharField(u"Текст", max_length=255)

    class Meta:
        verbose_name = u"Новость"
        verbose_name_plural = u"Новость"

    def __unicode__(self):
        return self.title


class Follower(models.Model):
    email = models.CharField(u'Email', max_length=255)
    created_at = models.DateField(u'Дата подписки', auto_now_add=True, editable=False)

    class Meta:
        verbose_name = u"Подписчик"
        verbose_name_plural = u"Подписчики"

    def __unicode__(self):
        return self.email

apps/legoteka/models.py
# coding: utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    title = models.CharField(_("Название"), max_length=255)

    class Meta:
        verbose_name = _(u"Категория")
        verbose_name_plural = _(u"Категории")

    def __unicode__(self):
        return self.title


class LegotekaItem(models.Model):
    category = models.ForeignKey(Category, verbose_name=_(u"Категория"))
    title = models.CharField(_("Название"), max_length=255)
    photo = models.ImageField(u"Фотография", upload_to='legoteka/')
    code = models.CharField(_("Код"), max_length=255, blank=True)
    available = models.BooleanField(_("В наличии"), default=True)
    holder = models.CharField(_(u"У кого на руках"), max_length=255, blank=True)
    receiving_date = models.DateField(_(u"Дата получения"), blank=True, null=True)
    return_date = models.DateField(_(u"Дата возврата"), blank=True, null=True)

    class Meta:
        verbose_name = _(u"Предмет леготеки")
        verbose_name_plural = _(u"Предметы леготеки")

    def __unicode__(self):
        return self.title


class LegotekaItemOrder(models.Model):
    item = models.ForeignKey(LegotekaItem, verbose_name=_("Предмет"))
    name = models.CharField(_(u"ФИО"), max_length=255)
    contacts = models.CharField(_("Телефон или email"), max_length=255)
    note = models.TextField(_(u"Примечание"), blank=True)

    class Meta:
        verbose_name = _(u"Заявка на предмет леготеки")
        verbose_name_plural = _(u"Заявки на предметы леготеки")

    def __unicode__(self):
        return self.name

apps/library/models.py
# coding: utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from redactor.fields import RedactorField


class Book(models.Model):
    title = models.CharField(_(u"Название"), max_length=255)
    description = models.TextField(u'Описание')
    book_file = models.FileField(_(u"Файл"), blank=True, upload_to='books/')
    holder = models.CharField(_(u"У кого на руках"), max_length=255, blank=True)
    receiving_date = models.DateField(_(u"Дата получения"), blank=True, null=True)
    return_date = models.DateField(_(u"Дата возврата"), blank=True, null=True)

    class Meta:
        verbose_name = _(u"Книга")
        verbose_name_plural = _(u"Книги")

    def __unicode__(self):
        return self.title


class BookOrder(models.Model):
    item = models.ForeignKey(Book, verbose_name=_("Книга"))
    name = models.CharField(_(u"ФИО"), max_length=255)
    contacts = models.CharField(_("Телефон или email"), max_length=255)
    note = models.CharField(_(u"Примечание"), max_length=255, blank=True)

    class Meta:
        verbose_name = _(u"Заявка на книгу")
        verbose_name_plural = _(u"Заявки на книги")

    def __unicode__(self):
        return self.name

apps/base/forms.py
# coding: utf-8
from django import forms

from apps.base.models import Follower


class NewFollowerForm(forms.ModelForm):
    class Meta:
        model = Follower
        exclude = ()
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form_email', 'placeholder': u'Ваш E-mail'}),
        }

apps/legoteka/forms.py
# coding: utf-8

from django import forms
from apps.legoteka.models import LegotekaItemOrder


class LegotekaOrderForm(forms.ModelForm):
    class Meta:
        model = LegotekaItemOrder
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form_name', 'placeholder': u'ФИО', 'required': 'True'}),
            'contacts': forms.TextInput(attrs={'class': 'form_contacts', 'placeholder': u'E-mail или телефон',
                                               'required': 'True'}),
            'note': forms.Textarea(attrs={'class': 'form_note', 'placeholder': u'Комментарий', 'required': 'True'}),
        }

apps/library/forms.py
# coding: utf-8
from django import forms

from models import BookOrder


class BookOrderForm(forms.ModelForm):
    class Meta:
        model = BookOrder
        exclude = ()
        widgets = {
            'name': forms.TextInput(attrs={'class':'form_name', 'placeholder':u'ФИО'}),
            'contacts': forms.TextInput(attrs={'class':'form_contacts', 'placeholder':u'E-mail или телефон'}),
            'note': forms.Textarea(attrs={'class':'form_note', 'placeholder':u'Комментарий'}),
        }

apps/base/views.py
import json

from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render
from django.utils import timezone

from apps.base.models import News
from apps.event.models import Event
from apps.base.forms import NewFollowerForm


def home(request):
    slider_events = Event.objects.all()
    events = Event.objects.all().values('id', 'title', 'date', 'type')
    print(events)
    events = json.dumps(list(events), cls=DjangoJSONEncoder)
    print(events)
    news = News.objects.all()[:10]
    folow_form = NewFollowerForm(request.POST or None)
    if folow_form.is_valid():
        folow_form.save()
    return render(request, 'base/home.html', locals())

apps/legoteka/views.py
from django.shortcuts import render
from apps.legoteka.forms import LegotekaOrderForm
from .models import LegotekaItem, Category


def home(request):
    categories = Category.objects.all()
    category = Category.objects.first()
    items = LegotekaItem.objects.filter(category=category)
    form = LegotekaOrderForm(request.POST or None)
    if form.is_valid():
        form.save()
    return render(request, 'legoteka.html', locals())


def legoteka_by_category(request, pk):
    category = Category.objects.get(pk=pk)
    categories = Category.objects.all()
    items = LegotekaItem.objects.filter(category=category)
    form = LegotekaOrderForm(request.POST or None)
    if form.is_valid():
        form.save()
    return render(request, 'legoteka.html', locals())

apps/library/views.py
# coding: utf-8
from django.shortcuts import render
from forms import BookOrderForm
from models import Book


def book_list(request):
    message = None
    books = Book.objects.all()
    get_book_form = BookOrderForm(request.POST or None, request.GET or None)
    if request.method == 'POST':
        if get_book_form.is_valid():
            get_book_form.save()
            message = 'Запрос отправлен'

    return render(request, 'library.html', {'books': books, 'get_book_form': get_book_form, 'message': message})

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    {% block meta_tags %}
        <meta property="og:url" content="" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="When Great Minds Don’t Think Alike" />
        <meta property="og:description" content="How much does culture influence creative thinking?" />
        <meta property="og:image" content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />
    {% endblock meta_tags %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    {% block extra_css %}{% endblock %}
</head>
<body>

{% block header %}
{% endblock header %}
<main>
{% block body %}
{% endblock body %}
</main>
{% block footer %}
{% endblock footer %}
    <script src="{% static 'js/jquery-2.2.2.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{%  static 'js/slick.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
{% block extra_js %}{% endblock extra_js %}
</body>
</html>

templates/financial_event.html
{% extends 'layout.html' %}
{% load i18n l10n static %}

{% block title %}{% trans 'Финансовые ресуры' %}{% endblock %}
{% block body %}
    {% for book in books %}
        <p>{{ book.title }}
        {{ book.description }}
        {% if book.book_file %}
            <a href="?book_id={{ book.id }}">Отправить заявку</a>
        {% endif %}</p>
    {% endfor %}
    <form action="#" method="post">
    {% csrf_token %}
    {{ event_take_part_form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/humanitarian_aid.html
{% extends 'layout.html' %}
{% load i18n l10n static %}

{% block title %}{% trans 'Гуманитарная помощь' %}{% endblock %}
{% block body %}
    <div class="container">
        <h2>Гуманитарная помощь</h2>
        <div class="row">
            <div class="col-md-4">
                <ul id="myTabs" class="nav nav-pills nav-stacked" role="tablist">
                    <li role="presentation" class="">
                        <a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="false">Детям</a>
                    </li>
                    <li role="presentation" class="dropdown">
                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown" aria-controls="myTabDrop1-contents" aria-expanded="true">
                            Потенциальным спонсорам
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="myTabDrop1" id="myTabDrop1-contents">
                            <li class="">
                                <a href="#dropdown1" role="tab" id="dropdown1-tab" data-toggle="tab" aria-controls="dropdown1">Центру</a>
                            </li>
                            <li class="">
                                <a href="#dropdown2" role="tab" id="dropdown2-tab" data-toggle="tab" aria-controls="dropdown2">Детям</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="col-md-8">
                <div id="myTabContent" class="tab-content">
                    <div role="tabpanel" class="tab-pane fade" id="home" aria-labelledby="home-tab">
                    <table class="library_table" width="100%">
                        <tr>
                            <th>Название</th>
                            <th>Описание</th>
                            <th>Форма</th>
                        </tr>
                        {% for item in for_kids %}
                        <tr>
                            <td>{{ item.title }}</td>
                            <td>{{ item.description }}</td>
                            <td>
                                <button type="button" class="" data-toggle="modal" data-item_id="{{ book.id }}" data-target="#myModal">
                                    Подать заявку
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                    </div>
                    {% regroup for_sponsors by get_type_display as sorted_items %}
                    {% for item in sorted_items %}
                        <div role="tabpanel" class="tab-pane fade" id="dropdown{{ forloop.counter }}" aria-labelledby="home-tab">
                            <h3>{{ item.grouper }}</h3>
                            <br>
                            <table class="library_table" width="100%">
                                <tr>
                                    <th>Название</th>
                                    <th>Описание</th>
                                    <th>Форма</th>
                                </tr>
                                {% for i in item.list %}
                                    <tr>
                                        <td>{{ i.title }}</td>
                                        <td>{{ i.description }}</td>
                                        <td>
                                            <button type="button" class="" data-toggle="modal" data-item_id="{{ book.id }}" data-target="#myModal">
                                                Подать заявку
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Заполните форму</h4>
        </div>
        <div class="modal-body">
            <form method="post">
                {% csrf_token %}
                {{ get_book_form.name }}
                {{ get_book_form.contacts }}
                {{ get_book_form.note }}
                <input type="submit">
            </form>
        </div>
    </div>

{% endblock %}

templates/layout.html
{% extends 'base.html' %}
{% load i18n static %}

{% block header %}
    {% include 'base/partials/header.html' %}
{% endblock header %}

{% block footer %}
    {% include 'base/partials/footer.html' %}
{% endblock footer %}

templates/legoteka.html
{% extends 'layout.html' %}
{% load i18n l10n static %}

{% block title %}{% trans 'Леготека' %}{% endblock %}
{% block body %}
    <div class="container">
        <h2>Леготека</h2>
        <div class="row">
            <div class="col-md-4">
                <ul class="nav nav-pills nav-stacked" role="tablist">
                    {% for category in categories %}
                        <li role="presentation" id="pill-{{ category.pk }}">
                            <a href="{% url 'legoteka:by_category' category.pk %}">{{ category }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-8">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane" id="tab-{{ category.pk }}">
                        {% for item in items %}
                            <div class="col-md-4 col-sm-12">
                                <div class="thumbnail">
                                    <img src="{{ item.photo.url }}" class="legotech_image" height="150px" width="150px">
                                    <div class="caption">
                                        <span><p>{{ item|truncatechars:60 }}</p><h6>{% if item.available %}в наличии{% else %}нет в наличии{% endif %}</h6></span>
                                        <button type="button" {% if not item.available %}disabled{% endif %} class="btn btn-primary btn-lg order-btn" data-item_id="{{ item.id }}" data-target="#myModal">
                                            Подать заявку
                                        </button>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Заполните форму</h4>
                </div>
                <div class="modal-body">
                    <form method="post" id="order-item">
                        {% csrf_token %}
                        <div style="display: none;">{{ form.item }}</div>
                        {{ form.name }}
                        {{ form.contacts }}
                        {{ form.note }}
                        <input type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div>
    </div>
    <div class="popup_wrap"></div>
{% endblock %}
{% block extra_js %}
    <script>
        $(function(){
            var cat = {{ category.pk }};
            $('#pill-'+cat).addClass('active');
            $('#tab-'+cat).addClass('active');
            $('.order-btn').on('click', function(){
                $(this).addClass('chosen-item');
                var item = $(this).attr('data-item_id');
                $("#id_item").val(item);
                $('#myModal').modal('show');
            });
        });
    </script>
{% endblock %}

templates/library.html
{% extends 'layout.html' %}
{% load i18n l10n static %}

{% block title %}{% trans 'Библиотека' %}{% endblock %}
{% block body %}
    <div class="container">
        <h2>Библиотека</h2>
        <table class="library_table" width="100%">
            <tr class="table_header">
                <th>Название книги</th>
                <th>Краткое описание</th>
                <th>На руках у:</th>
                <th>Дата получения</th>
                <th>Дата возврата</th>
                <th>Скачать или <br> отправить заявку</th>
            </tr>
            {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.description }}</td>
                    <td>{{ book.holder }}</td>
                    <td>{{ book.receiving_date }}</td>
                    <td>{{ book.return_date }}</td>
                    <td>{% if book.book_file %}
                        <a href="{{ book.book_file.url }}">Скачать книгу</a>
                    {% else %}
                        <button type="button" class="order-btn" data-item_id="{{ book.id }}"
                                data-target="#myModal">
                            Подать заявку
                        </button>
                    {% endif %}</td>
                <tr>
            {% endfor %}
        </table>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Заполните форму</h4>
                    </div>
                    <div class="modal-body">
                        <form method="post", id="order-item">
                            {% csrf_token %}
                            <div style="display: none;">{{ get_book_form.item }}</div>
                            {{ get_book_form.name }}
                            {{ get_book_form.contacts }}
                            {{ get_book_form.note }}
                            <input type="submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="popup_wrap"></div>
{% endblock %}
{% block extra_js %}
    <script>
        $(function(){
            $('.order-btn').on('click', function(){
                $(this).addClass('chosen-item');
                var item = $(this).attr('data-item_id');
                $("#id_item").val(item);
                $('#myModal').modal('show');
            });
        });
    </script>
{% endblock %}