api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

import views as api_views


urlpatterns = [
    url(r'^feedback/new/$', api_views.create_feedback),
    url(r'^books/$', api_views.books),
]

apps/base/urls.py
from django.conf.urls import url
from views import home

urlpatterns = [url(r'^$', home, name='home'), ]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from project import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.base.urls', namespace='base')),
    url(r'^legoteka/', include('apps.legoteka.urls', namespace='legoteka')),
    url(r'^humanitarian_aid/', include('apps.aid.urls', namespace='humanitarian_aid')),
    url(r'^library/', include('apps.library.urls', namespace='library')),
    url(r'^financial/', include('apps.financial.urls', namespace='financial')),
    url(r'^api/', include('api.urls')),
    url(r'^pages/(\S+)/$', 'apps.pages.views.pages_detail', name='pages_detail'),
    url(r'^redactor/', include('redactor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from redactor.fields import RedactorField


class News(models.Model):
    title = models.CharField(u"Заголовок", max_length=255)
    photo = models.ImageField(u"Фотография", upload_to='news/')
    text = models.CharField(u"Текст", max_length=255)

    class Meta:
        verbose_name = u"Новость"
        verbose_name_plural = u"Новость"

    def __unicode__(self):
        return self.title


class Follower(models.Model):
    email = models.CharField(u'Email', max_length=255)
    created_at = models.DateField(u'Дата подписки', auto_now_add=True, editable=False)

    class Meta:
        verbose_name = u"Подписчик"
        verbose_name_plural = u"Подписчики"

    def __unicode__(self):
        return self.email

apps/base/forms.py
# coding: utf-8
from django import forms

from apps.base.models import Follower


class NewFollowerForm(forms.ModelForm):
    class Meta:
        model = Follower
        exclude = ()
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form_email', 'placeholder': u'Ваш E-mail'}),
        }

apps/base/views.py
import json

from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render
from django.utils import timezone

from apps.base.models import News
from apps.event.models import Event
from apps.base.forms import NewFollowerForm


def home(request):
    slider_events = Event.objects.all()
    events = Event.objects.all().values('id', 'title', 'date', 'type')
    print(events)
    events = json.dumps(list(events), cls=DjangoJSONEncoder)
    print(events)
    news = News.objects.all()[:10]
    folow_form = NewFollowerForm(request.POST or None)
    if folow_form.is_valid():
        folow_form.save()
    return render(request, 'base/home.html', locals())

templates/base/partials/footer.html
{% load static %}
<footer class="">
    <div class="container">
        <div class="row">
            <div class="footer_wrap">
                <div class="footer_menu_wrap">
                    <a href="{% url 'base:home' %}" class="header_menu_items">Главная</a>
                    <a href="#" class="header_menu_items">О нас</a>
                    <a href="{% url 'legoteka:home' %}" class="header_menu_items">Леготека</a>
                    <a href="#" class="header_menu_items">Финансовые ресурсы</a>
                    <a href="{% url 'humanitarian_aid:home' %}" class="header_menu_items">Гумпомощь</a>
                    <a href="#" class="header_menu_items">Информация</a>
                </div>
                <div class="footer_social_block">
                    <a href="#"><img src="{% static 'img/fb.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/inst.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/tw.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icn_gplus.png' %}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/base/partials/header.html
{% load static %}
<header>
    <nav class="header_nav_menu">
        <div class="container">
            <div class="header_wrap">
                <div class="main_logo">
                    <a href="{% url 'base:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
                <div class="header_menu_wrap">
                    <a href="{% url 'base:home' %}" class="header_menu_items">Главная</a>
                    <a href="{% url 'pages_detail' 'o-nas' %}" class="header_menu_items">О нас</a>
                    <a href="{% url 'legoteka:home' %}" class="header_menu_items">Леготека</a>
                    <a href="{% url 'financial:home' %}" class="header_menu_items">Финансовые ресурсы</a>
                    <a href="{% url 'humanitarian_aid:home' %}" class="header_menu_items">Гумпомощь</a>
                    <a href="{% url 'library:home' %}" class="header_menu_items">Библиотека</a>
                </div>
            </div>
        </div>
    </nav>
</header>